### ISSUE TITLE
Add log level setting

### ISSUE THREAD

**Issue by gasci** [conformist-mw/django-query-counter#21]
Hi, thank you for this useful plugin.

It would be great to print the duplicated queries according to the log level of the logger. Is it possible to do that already? Instead of printing the stats, you can exploit the logging library.

**Comment by conformist-mw** [comment]
Thanks for your interest in this plugin.
 
Yes, in general it is possible to implement logging.level dependent output, but I think if the idea is to include the plugin in the requirements for production environment, it's not a good idea since this plugin was meant to be used during development — counting queries and analyzing them is not free, it will affect performance.

On the other hand — it could be optionally included to see the number of queries on real data (very often it is hard to reproduce production environment data volumes locally). 

I'll think about how to make it more convenient.

**Comment by gasci** [comment]
Thanks for the quick answer. Does plugin disable itself when `DEBUG=False,` then? @conformist-mw

**Comment by conformist-mw** [comment]
No. Like all such utilities they are enabled depending on the DEBUG setting - explicit is better than implicit :)

**Comment by gasci** [comment]
Okay, then. My workaround is adding it only in the dev group with poetry and the production environment doesn't install the dev dependencies. Thank you for your time.

**Comment by gasci** [comment]
Is there a way to disable print-outs on demand without deleting the plugin? @conformist-mw

**Comment by conformist-mw** [comment]
Not at the moment, but there are plans to add such a setting.
